// user data

List userData = [
  {
    "name": "Sonya Leena",
    "firstName": "Sonya",
    "nickname": "@sonia_l",
    "logo": "images/2w.jpg",
    "img": "images/1w.jpg",
    "country": "Dubai, UAE",
    "desc": "You can never dull my sparkie 💫",
    "isLiked": true,
    "isLive": true,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Adam",
    "nickname": "@adam_ad",
    "logo": "images/1m.jpg",
    "img": "images/3m.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Andrew Dewitt",
    "firstName": "Andrew",
    "nickname": "@andrew_d71",
    "logo": "images/3m.jpg",
    "img": "images/1m.jpg",
    "country": "Overland Park,Ks",
    "desc": "The unxpected moment is always sweeter!",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Nicole Seggall",
    "firstName": "Nicole",
    "nickname": "@nicole",
    "logo": "images/4w.jpg",
    "img": "images/5w.jpg",
    "country": "New Delhi ,India",
    "desc": "Life is Life ...",
    "isLiked": true,
    "isLive": false,
  },
  {
    "name": "Athena Parker",
    "firstName": "Athena",
    "nickname": "@parkkker",
    "logo": "images/3w.jpg",
    "img": "images/2w.jpg",
    "country": "Lawrence ,Ks",
    "desc": "Lifestyle Blogger join as",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "kamisa Elyien",
    "firstName": "kamisa",
    "nickname": "@elyien",
    "logo": "images/5w.jpg",
    "img": "images/4w.jpg",
    "country": "Oran ,Algeria",
    "desc": "I ❤️ Travel",
    "isLiked": true,
    "isLive": false,
  },
  {
    "name": "Elen Gabriels",
    "firstName": "Elen",
    "nickname": "@elyien",
    "logo": "images/1w.jpg",
    "img": "images/5w.jpg",
    "country": "Mostaganem ,Algeria",
    "desc": "You can never dull my sparkie 💫",
    "isLiked": true,
    "isLive": false,
  },
  {
    "name": "Maradona Ilipsis",
    "firstName": "Maradona",
    "nickname": "@elyien",
    "logo": "images/4m.jpg",
    "img": "images/4w.jpg",
    "country": "Alger ,Algeria",
    "desc": "Life is Life ...",
    "isLiked": true,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Adam",
    "nickname": "@adam_ad",
    "logo": "images/1m.jpg",
    "img": "images/3m.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
];
List storyData = [
  {
    "name": "Sonya Leena",
    "firstName": "Sonya",
    "nickname": "@sonia_l",
    "logo": "images/2w.jpg",
    "img": "images/1w.jpg",
    "country": "Dubai, UAE",
    "desc": "You can never dull my sparkie 💫",
    "isLiked": true,
    "isLive": true,
  },
  {
    "name": "Sonya Leena",
    "firstName": "Sonya",
    "nickname": "@sonia_l",
    "logo": "images/2w.jpg",
    "img": "images/1w.jpg",
    "country": "Dubai, UAE",
    "desc": "You can never dull my sparkie 💫",
    "isLiked": true,
    "isLive": true,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Adam",
    "nickname": "@adam_ad",
    "logo": "images/1m.jpg",
    "img": "images/3m.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Andrew Dewitt",
    "firstName": "Andrew",
    "nickname": "@andrew_d71",
    "logo": "images/3m.jpg",
    "img": "images/1m.jpg",
    "country": "Overland Park,Ks",
    "desc": "The unxpected moment is always sweeter!",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Nicole Seggall",
    "firstName": "Nicole",
    "nickname": "@nicole",
    "logo": "images/4w.jpg",
    "img": "images/5w.jpg",
    "country": "New Delhi ,India",
    "desc": "Life is Life ...",
    "isLiked": true,
    "isLive": false,
  },
  {
    "name": "Athena Parker",
    "firstName": "Athena",
    "nickname": "@parkkker",
    "logo": "images/3w.jpg",
    "img": "images/2w.jpg",
    "country": "Lawrence ,Ks",
    "desc": "Lifestyle Blogger join as",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "kamisa Elyien",
    "firstName": "kamisa",
    "nickname": "@elyien",
    "logo": "images/5w.jpg",
    "img": "images/4w.jpg",
    "country": "Oran ,Algeria",
    "desc": "I ❤️ Travel",
    "isLiked": true,
    "isLive": false,
  },
  {
    "name": "Elen Gabriels",
    "firstName": "Elen",
    "nickname": "@elyien",
    "logo": "images/1w.jpg",
    "img": "images/5w.jpg",
    "country": "Mostaganem ,Algeria",
    "desc": "You can never dull my sparkie 💫",
    "isLiked": true,
    "isLive": false,
  },
  {
    "name": "Maradona Ilipsis",
    "firstName": "Maradona",
    "nickname": "@elyien",
    "logo": "images/4m.jpg",
    "img": "images/4w.jpg",
    "country": "Alger ,Algeria",
    "desc": "Life is Life ...",
    "isLiked": true,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Adam",
    "nickname": "@adam_ad",
    "logo": "images/1m.jpg",
    "img": "images/3m.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
];

List storyHighlights = [
  {},
  {
    "name": "Garden",
    "img": "images/1.jpg",
  },
  {
    "name": "Cameras",
    "img": "images/2.jpg",
  },
  {
    "name": "wildlife",
    "img": "images/3.jpg",
  },
];
